### ISSUE TITLE
Mqtt config

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard-gateway#100]
Hi

I have updated the thingsboard gateway to 1.4.0
I wouldn't like to use the remote mqtt config, I would like to use mqtt-config.json like tb-gateaway 1.2.2 
Can I use it?

**Comment by mp-loki** [comment]
Yes, however it is slightly different from 1.2, because tb-gateway v.1.4.0 support multi-tenant mode. 
Just check out the [tb-gateway.yml](https://github.com/thingsboard/thingsboard-gateway/blob/master/src/main/resources/tb-gateway.yml) from latest version and update the last few lines like:
```yaml
      remoteConfiguration: false
      extensions:
        -
          id: "mqtt"
          type: "MQTT"
          extensionConfiguration: mqtt-config.json
```
It is important to set **remoteConfiguration: false**, otherwise the configuration from TB GUI will be applied.
