### ISSUE TITLE
[HELP] How to get Temperature and Humidity from SHT20 sensor

### ISSUE THREAD

**Issue by 11208** [thingsboard/thingsboard-gateway#1016]
**Describe the issue**
Create description about your issue, and your actions to solve it.
I have succcesfully connect modbus device -- SHT20(XY-MD02) to tb_gateway. But the thing is only temperature data reach TB server. 

I check with Pymodbus REPL, seems like address 2 is return IllegalAddress. That's why humidity data not send to server.
```
$ pymodbus.console serial --port /dev/ttyS0 --baudrate 9600 --timeout 2

> client.read_input_registers count=2 address=1 unit=1
{
    "registers": [
        290,
        393
    ]
}

> client.read_input_registers count=2 address=2 unit=1
{
    "original_function_code": "4 (0x4)",
    "error_function_code": "132 (0x84)",
    "exception code": 2,
    "message": "IllegalAddress"
}
```

In that case, How to config modbus.json for timeseries with response like this "registers": [290,393]?

**Configuration** (Attach your configuration file)
tb_gateway.yaml
```
thingsboard:
  host: IP
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: true
    statsSendPeriodInSeconds: 3600
#    configuration: statistics.json
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: TOKEN
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
#  type: sqlite
#  data_file_path: ./data/data.db
#  messages_ttl_check_in_hours: 1
#  messages_ttl_in_days: 7
grpc:
"/etc/thingsboard-gateway/config/tb_gateway.yaml" 137L, 2659B                                                                                                                       16,33         Top
```
modbus.json
```
{
  "master": {
    "slaves": [
      {
        "unitId": 1,
        "deviceName": "Station-1",
        "deviceType": "sensors",
        "timeseriesPollPeriod": 5000,
        "sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "timeseries": [
          {
            "tag": "temperature",
            "type": "16uint",
            "functionCode": 4,
            "registerCount": 2,
            "address": 1,
            "devider": 10
          },
          {
            "tag": "humidity",
            "type": "16uint",
            "functionCode": 4,
            "registerCount": 2,
            "address": 2,
            "divider": 10
          }
        ],
        "host": null,
        "port": "/dev/ttyS0",
        "type": "serial",
        "method": "rtu",
        "timeout": 35,
        "byteOrder": "BIG",
        "wordOrder": "BIG",
        "retries": true,
        "retryOnEmpty": true,
        "retryOnInvalid": true,
        "baudrate": 9600,
        "pollPeriod": 5000
      }
    ],
    "slave": null
  }
}
```
**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]
MODBUS Converter

**Error traceback (If it was raised):**
Log from converter.log
```
""2022-12-03 22:47:44" - |ERROR| - [bytes_modbus_uplink_converter.py] - bytes_modbus_uplink_converter - convert - 84 - Modbus Error: [Input/Output] No Response received from the remote unit/Unable >
NoneType: None
""2022-12-03 22:47:44" - |ERROR| - [bytes_modbus_uplink_converter.py] - bytes_modbus_uplink_converter - convert - 84 - Exception Response(132, 4, IllegalAddress)"
NoneType: None
```

**Versions (please complete the following information):**
 - OS: RPI 3B+ Debian
 - Thingsboard IoT Gateway version 3.2
 - Python version 3.9
