### ISSUE TITLE
[HELP] How to make an rpc to turn on/off rs485 relay.

### ISSUE THREAD

**Issue by 11208** [thingsboard/thingsboard-gateway#1024]
**Describe the issue**
I am trying to make an rpc to turn on/off rs485 relay. By make a sample call to /api/rpc/oneway/{deviceId} via swagger UI.
```
curl -X 'POST' \
  'http://TBIP:8080/api/rpc/oneway/bb4ea390-779c-11ed-a204-c90b63d3218d' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-Authorization: Bearer TOKEN' \
  -d '{
  "method": "onSwitch",
  "params": true,
  "persistent": false,
  "timeout": 5000
}'
```
Then I check audit log and see post data.
```
{
  "entityId": "bb4ea390-779c-11ed-a204-c90b63d3218d",
  "oneWay": true,
  "method": "onSwitch",
  "params": "true"
}
```

But the gateway not trigger the relay.
Do I have to make any change to root rule chain?

I did try to trigger relay with pymodbus and it is working fine.
```
pymodbus.console serial --port /dev/ttyS0 --baudrate 9600 --timeout 2
client.write_coil value=1 address=0 unit=1
{
    "original_function_code": "5 (0x5)",
    "error": "[Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 4 bytes (1 received)"
}
```

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**
```
thingsboard:
  host: TBIP
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: true
    statsSendPeriodInSeconds: 3600
#    configuration: statistics.json
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: TOKEN
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:

-
    name: Modbus Connector for RELAY
    type: modbus
    configuration: modbus_serial.json
```
modbus_serial.json
```
{ "master": {
    "slaves": [
      {
        "unitId": 1,
        "deviceName": "Switch-1",
	"deviceType": "switch",
        "timeseriesPollPeriod": 5000,
        "sendDataOnlyOnChange": false,
	"connectAttemptTimeMs": 5000,
	"connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "rpc": [
          {
	    "tag": "onSwitch",
            "type": "bits",
            "functionCode": 5,
            "objectsCount": 1,
            "address": 0,
	    "value": 1
	  }
        ],
	"host": null,
        "port": "/dev/ttyS0",
        "type": "serial",
        "method": "rtu",
        "timeout": 35,
	"byteOrder": "BIG",
        "wordOrder": "BIG",
        "retries": true,
	"retryOnEmpty": true,
        "retryOnInvalid": true,
        "baudrate": 9600,
        "pollPeriod": 5000
      }
    ],
    "slave": null
  }
}
```

**Connector name (If you need help with some connector/converter):**
MODBUS Connector

**Error traceback (If it was raised):**

**Versions (please complete the following information):**
 - OS: Raspi 3B+
 - Thingsboard IoT Gateway version 3.2
 - Python version 3.9
