### ISSUE TITLE
How to only update  "deviceName" in modbus connector not insert a new one

### ISSUE THREAD

**Issue by 11208** [thingsboard/thingsboard-gateway#1073]
**Describe the issue**
When ever I tried to change the  "deviceName" in modbus.json then restart gateway, it add new device to thingsboard instead of update the name.

**Configuration** 
```
thingsboard:
  host: XX.XXX.XXX.XXX
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: true
    statsSendPeriodInSeconds: 3600
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: XXX
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:
  -
    name: Modbus Connector for SHT20
    type: modbus
    configuration: sht20.json
    ```

**Connector name (If you need help with some connector/converter):**
Modbus

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04
 - Thingsboard IoT Gateway version v3.2
 - Python version 3.9
