### ISSUE TITLE
Failed connecting gateway to Kepware Server.

### ISSUE THREAD

**Issue by fwaznad** [thingsboard/thingsboard-gateway#109]
hi @mp-loki @ashvayka ,

I installed tb-gateway on rasp pi. and try to implement opc ua connection with Kepware Server which is installed in my window PC. However the connection is failed.

```
2018-08-07 08:43:38,459 [main] ERROR o.t.g.e.opc.OpcUaServerMonitor - OPC-UA server connection failed!
        at org.thingsboard.gateway.extensions.opc.OpcUaServerMonitor.connect(OpcUaServerMonitor.java:107)
        at org.thingsboard.gateway.extensions.opc.DefaultOpcUaService.init(DefaultOpcUaService.java:67)
Caused by: org.eclipse.milo.opcua.stack.core.UaException: An error occurred verifying security.
        at org.eclipse.milo.opcua.stack.client.handlers.UaTcpClientAcknowledgeHandler.onError(UaTcpClientAcknowledgeHandler.java:290)
        at org.eclipse.milo.opcua.stack.client.handlers.UaTcpClientAcknowledgeHandler.decode(UaTcpClientAcknowledgeHandler.java:186)

```
tb-gateway.yml file
```
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "${GATEWAY_HOST:demo.thingsboard.io}"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "${GATEWAY_ACCESS_TOKEN:As6VolVwWB0lCe65Pp1U}"
      remoteConfiguration: false
      extensions:
        -
          id: "opc-ua"
          type: "OPC UA"
          extensionConfiguration: opc-config.json
```
opc-conf.json file as below
```
{  "servers": [
    {
      "applicationName": "Thingsboard OPC-UA client",
      "applicationUri": "",
      "host": "192.168.43.233",
      "port": 49320,
      "scanPeriodInSeconds": 10,
      "timeoutInMillis": 5000,
      "security": "Basic128Rsa15",
      "identity": {
        "type": "anonymous"
      },
      "keystore": {
        "type": "PKCS12",
        "location": "example.pfx",
        "fileContent": "",
        "password": "secret",
        "alias": "gateway",
        "keyPassword": "secret"
      },
      "mapping": [
        {
          "deviceNodePattern": "Kepware\\.KEPServerEX\\.V6\\.Painting\\.Oven",
          "deviceNamePattern": "Device1",
          "attributes": [
            {
              "key": "Fan",
              "type": "float",
              "value": "${Fan}"
            }
          ],
          "timeseries": [
            {
              "key": "Pressure",
              "type": "float",
              "value": "${Pressure}"
            }
          ]
        }
      ]
    }
  ]
}
```
Opc server config
![end](https://user-images.githubusercontent.com/42095161/43710224-a6a05246-99a1-11e8-8e7e-0d182b268181.png)
![cer](https://user-images.githubusercontent.com/42095161/43710227-a9a3acc2-99a1-11e8-9090-635b763e197f.png)

Kepware server Demo

![kep](https://user-images.githubusercontent.com/42095161/43710254-b5840802-99a1-11e8-96f9-ec40588ffd59.png)

In demo.thingsboard.org, it showed opcExstentionError

![tb](https://user-images.githubusercontent.com/42095161/43710454-4886c6c6-99a2-11e8-8e45-6f30c0ad0d62.png)
 
What configurations do I missed?

Regard
waz
