### ISSUE TITLE
Use Hot restart when use Docker

### ISSUE THREAD

**Issue by Javieral95** [thingsboard/thingsboard-gateway#1131]
**Describe the issue**
Hi everyone, I'm deploying a simple Proof of concepto using ThingsBoard server and the ThingsBoard IoT Gateway in the same machine. My deployment use a docker-compose.yml whose services are using the following images:

- thingsboard/tb-postgres:3.5.1
- thingsboard/tb-gateway:3.2

Cause Im using Docker Compose along with JSON configuration files in my project, I need to restart the container every time I make configuration changes and want to test them. I would like to leverage the "Hot Restart", but I have been unable to find a way to use it effectively with Docker.

I have attempted to use the `DEBUG `environment variable as a means to achieve "Hot Restart," but unfortunately, it doesn't seem to be working as expected. Despite setting DEBUG=true, the container does not automatically restart upon configuration changes.

**Configuration** (Attach your configuration file)
My docker compose file is the following:

```
version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres:3.5.1" # Also can use thingsboard/tb-cassandra (need minimum 4GB of RAM, but is recommended 8GB)
    ports:
      - "${THINGS_BOARD_PORT}:9090" # HTTP port
      - "${MQTT_PORT}:1883" # MQTT Port
      - "${RPC_PORT}:7070" # Edge RPC Port
      - "${UDP_PORT_MIN}-${UDP_PORT_MAX}:5683-5688/udp" # UDP Port (to exposed internal COAP and LwM2m2 port)
    environment:
      TB_QUEUE_TYPE: in-memory # Can use an external queue
    volumes:
      - ./data/mytb-data:/data
      - ./data/mytb-logs:/var/log/thingsboard
      #- ~/.mytb-data:/data # (Default) ThingsBoard database data directory
      #- ~/.mytb-logs:/var/log/thingsboard # (Default) ThingsBoard logs directory
    networks:
      - network_default      

  tb-gateway:
    restart: always
    image: "thingsboard/tb-gateway:3.2"
    # Ports (Required for REST connector)
    ports:
      - "${GATEWAY_PORT}:5000"
    environment:
      host: mytb
      port: 1883
      accessToken: \<TOKEN\>
      DEBUG: True
    volumes:
      - ./data/tb-gateway/config:/thingsboard_gateway/config
      - ./data/tb-gateway/logs:/thingsboard_gateway/logs
      - ./data/tb-gateway/extensions:/thingsboard_gateway/extensions
      #- ~/.tb-gateway/config:/thingsboard_gateway/config
      #- ~/.tb-gateway/logs:/thingsboard_gateway/logs
      #- ~/.tb-gateway/extensions:/thingsboard_gateway/extensions
    networks:
      - network_default

networks:
  network_default: 
    driver: bridge     
 ```

**Connector name (If you need help with some connector/converter):**
I`m using a Modbus connector, but I think that Its not relevant.

Thank you a lot! ThingsBoard and its Gateway are amazing applications! Congratulations to the entire team!

**Comment by samson0v** [comment]
Hi @Javieral95, thanks for your interest in ThingsBoard IoT Gateway!
You have to modify your docker-compose file (add command parameter):
```yaml
tb-gateway:
    restart: always
    image: "thingsboard/tb-gateway:3.2"
    command: ["/bin/sh", "-c", "python ./thingsboard_gateway/tb_gateway.py 1"]
    # Ports (Required for REST connector)
    ports:
      - "${GATEWAY_PORT}:5000"
    environment:
      host: mytb
      port: 1883
      accessToken: \<TOKEN\>
      DEBUG: True
    volumes:
      - ./data/tb-gateway/config:/thingsboard_gateway/config
      - ./data/tb-gateway/logs:/thingsboard_gateway/logs
      - ./data/tb-gateway/extensions:/thingsboard_gateway/extensions
      #- ~/.tb-gateway/config:/thingsboard_gateway/config
      #- ~/.tb-gateway/logs:/thingsboard_gateway/logs
      #- ~/.tb-gateway/extensions:/thingsboard_gateway/extensions
    networks:
      - network_default
```
