### ISSUE TITLE
[HELP] after upgrading I get "MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"

### ISSUE THREAD

**Issue by keestux** [thingsboard/thingsboard-gateway#1184]
**Describe the issue**
After upgrading to version 3.3 I'm seeing the following message in my syslog. After upgrading to version 3.4 the messages are still produced.
```
Sep 30 19:04:30 my.example.com python3[70652]: ""2023-09-30 19:04:30" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
```

Is this maybe a new error message for a missing MQTT configuration?

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**
```
root@test:~# cat /etc/thingsboard-gateway/config/tb_gateway.yaml | grep -v '^#'
thingsboard:
  host: thingsboard.cloud
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: true
    statsSendPeriodInSeconds: 3600
    configuration: statistics.json
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: PUT_YOUR_GW_ACCESS_TOKEN_HERE
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json
```

**Connector name (If you need help with some connector/converter):**
[MQTT Connector]

syslog messages
```
Sep 30 19:12:36 my.example.com python3[70652]: ""2023-09-30 19:12:36" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
```

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04
 - Thingsboard IoT Gateway version: 3.4
 - Python version: 3.10.12
