### ISSUE TITLE
[HELP] Implementing custom connector that read data from serial port

### ISSUE THREAD

**Issue by ktran1005** [thingsboard/thingsboard-gateway#1291]
**Describe the issue**
HI ThingsBoard-gateway team, I am implementing a custom connector to connect to my serial port on my device, read the data and push to the edge. I followed the document from Thingsboard-gateway document to implement it. At the moment, I just hard-coded the data that the sensor will generate. I expected I will see this data on my "edge" server but it seems like the edge server does not receive this data (it is still in inactive state). The first highlight text below is the text got generated from the gateway and I assumed that the got parsed correctly. I expected to see this number on the latest telemetry in my gateway but nothing happened.

```text
"2024-01-31 18:04:18" - |INFO| - [custom_serial_converter.py] - custom_serial_converter - convert - 150 - Converted data: {'deviceName': 'CustomSerialDevice1', 'deviceType': 'default', 'attributes': [], 'telemetry': [{'test': 123, 'ts': 1706742258308, 'values': {'test': 123}}]}"
```

**Configuration** (Attach your configuration file)
```yaml
thingsboard:
  host: localhost
  port: 8080
  remoteShell: false
  remoteConfiguration: false
  statsSendPeriodInSeconds: 3600
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: ....
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:

  -
   name: Custom Serial Connector
   type: serial
   configuration: custom_serial.json
   class: CustomSerialConnector
```

**Here is my custom convert method**
```python
    def convert(self, config, data: bytes):
        global byteBuffer, byteBufferLength

        # Constants
        OBJ_STRUCT_SIZE_BYTES = 12;
        BYTE_VEC_ACC_MAX_SIZE = 2**15;
        MMWDEMO_UART_MSG_DETECTED_POINTS = 1;
        MMWDEMO_UART_MSG_RANGE_PROFILE   = 2;
        maxBufferSize = 2**15;
        tlvHeaderLengthInBytes = 8;
        pointLengthInBytes = 16;
        magicWord = [2, 1, 4, 3, 6, 5, 8, 7]
        
        # Initialize variables
        magicOK = 0 # Checks if magic number has been read
        dataOK = 0 # Checks if the data has been read correctly
        frameNumber = 0
        detObj = {}

        keys = ['attributes', 'telemetry']
        for key in keys:
            self.result_dict[key] = []
            if self.__config.get(key) is not None:
                for config_object in self.__config.get(key):
                    now = int(round(time.time()*1000))
                    converted_data = {config_object['key']: 123, "ts": now, "values": {"test": 123}}
                    self.result_dict[key].append(converted_data)
        log.info("Converted data: %s", self.result_dict)
        return self.result_dict
```
** Here is SerialConnector configuration**
```json
{
  "name": "Custom serial connector",
  "devices": [
    {
      "name": "CustomSerialDevice1",
      "type": "default",
      "port": "/dev/ttyACM1",
      "baudrate": 921600,
      "converter": "CustomSerialUplinkConverter",
      "telementry": [],
      "attributes": [
        {
          "key": "SerialNumber",
          "type": "string"
        }
      ],
      "attributeUpdates": []
    }
  ]
}
```

I look forward to hearing any suggestions from you guys. Thank you in advanced!

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04.6]
 - Thingsboard IoT Gateway version [e.g. 3.4.4]
 - Python version[e.g. 3.10]
