### ISSUE TITLE
[BUG] Connection lost after changing General Configuration

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1331]
**Describe the bug**
I encountered a critical issue with the gateway configuration that leads to loss of connectivity and necessitates a container reset. This problem arises when I modify the General Configuration settings of a newly set up gateway, specifically enabling the Remote Shell option to "true." Following this adjustment, the gateway becomes inaccessible. Attempts to regain connection, including restarting the gateway container, prove futile. The only remedy is to delete and recreate the docker container. Upon setting up a new container, the connection is restored, and the remote shell functionality is operational.

Moreover, since the introduction of cloud-based gateway configuration updates (replacing the previous YAML file setup), I have faced challenges in synchronizing the cloud settings with the gateway's local settings. This has raised concerns about the effectiveness of the new configuration process.

**Questions:**
Has anyone else experienced similar issues with connection loss after enabling the remote shell setting?
Are there known problems related to synchronizing cloud settings with the gateway since the shift from YAML file configuration to cloud-based configuration?

**Steps to Reproduce:**
1. Set up a new gateway.
2. In the General Configuration, change the Remote Shell setting to "true."
3. Observe the loss of connection to the gateway. For example, with a RPC Ping.

**Expected Behavior:**
The gateway should remain accessible, and the remote shell functionality should be enabled without losing the connection or requiring a container reset.

**Actual Behavior:**
The connection to the gateway is lost upon enabling the remote shell setting. The connection cannot be re-established without deleting and creating a new docker container.

**Workaround:**
Deleting the existing gateway container and creating a new one restores the connection and enables the remote shell functionality.

**Error traceback (If available):**
```shell
tb-gateway  | Cannot load GRPC connector!
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 218 - Gateway starting...
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 223 - ThingsBoard IoT gateway version: 0.0
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 309 - Gateway started.
tb-gateway  | 2024-03-12 07:59:30 - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - _load_connectors - 844 - Connectors - not found!
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 181 - Subscribed to *|* with id 1 for device *
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - __init__ - 65 - Remote Configurator started
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_updater.py] - tb_updater - check_for_new_version - 84 - 3.4.5
tb-gateway  | 2024-03-12 07:59:30 - |INFO| - [tb_updater.py] - tb_updater - check_for_new_version - 86 -
tb-gateway  |
tb-gateway  | [===UPDATE===]
tb-gateway  |
tb-gateway  |  New version 3.4.5 is available!
tb-gateway  |
tb-gateway  | [===UPDATE===]
tb-gateway  |
tb-gateway  |
tb-gateway  | 2024-03-12 07:59:30 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - callback - 111 - Cannot fetch version number from server! Version number set to 0.0
tb-gateway  | 2024-03-12 07:59:31 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - process_config_request - 242 - Configuration update request received.
tb-gateway  | 2024-03-12 07:59:36 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __rpc_gateway_processing - 1269 - Received RPC request to the gateway, id: 0, method: gateway_ping
tb-gateway  | 2024-03-12 07:59:36 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __rpc_gateway_processing - 1276 - Remote shell is disabled.
tb-gateway  | 2024-03-12 07:59:56 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __process_remote_logging_update - 607 - Remote logging has being deactivated.
tb-gateway  | 2024-03-12 07:59:56 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - process_config_request - 242 - Configuration update request received.
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler databaseHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler serviceHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler connectorHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler converterHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler tb_connectionHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler storageHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler extensionHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 07:59:56 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_unsubscribe - 189 - Unsubscribed from *|*, subscription id '*'
tb-gateway  | 2024-03-12 07:59:57 - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - init_remote_shell - 419 - Remote shell is enabled. Please be carefully with this feature.
```

**Versions (please complete the following information):**
 - OS: Windows 10
 - Thingsboard IoT Gateway version: Docker Image 3.4.5

**Comment by samy4sam** [comment]
Hi @samson0v 
I tried it again on a linux server with the same result. There is no connection after updating the Shell Settings.

tb_gateway.json:
```yaml
{
  "thingsboard": {
    "host": "mqtt.thingsboard.cloud",
    "port": 1883,
    "remoteShell": true,
    "remoteConfiguration": true,
    "statistics": {
      "enable": true,
      "statsSendPeriodInSeconds": 3600
    },
    "deviceFiltering": {
      "enable": false,
      "filterFile": "list.json"
    },
    "maxPayloadSizeBytes": 1024,
    "minPackSendDelayMS": 200,
    "minPackSizeToSend": 500,
    "checkConnectorsConfigurationInSeconds": 60,
    "handleDeviceRenaming": true,
    "security": {
      "type": "accessToken",
      "accessToken": "<MY_TOKEN>"
    },
    "qos": 1,
    "checkingDeviceActivity": {
      "checkDeviceInactivity": false,
      "inactivityTimeoutSeconds": 200,
      "inactivityCheckPeriodSeconds": 500
    },
    "ts": 1710258944803
  },
  "storage": {
    "type": "memory",
    "read_records_count": 100,
    "max_records_count": 100000,
    "data_folder_path": "./data/",
    "max_file_count": 10,
    "max_read_records_count": 10,
    "max_records_per_file": 10000,
    "data_file_path": "./data/data.db",
    "messages_ttl_check_in_hours": 1,
    "messages_ttl_in_days": 7,
    "ts": 1710258944803
  },
  "grpc": {
    "enabled": false,
    "serverPort": 9595,
    "keepaliveTimeMs": 10000,
    "keepaliveTimeoutMs": 5000,
    "keepalivePermitWithoutCalls": true,
    "maxPingsWithoutData": 0,
    "minTimeBetweenPingsMs": 10000,
    "minPingIntervalWithoutDataMs": 5000,
    "keepAliveTimeMs": 10000,
    "keepAliveTimeoutMs": 5000
  },
  "connectors": []
}
```

When I try to enable the remote logs I have another bug. When I press save I see this on the linux server:
```shell
tb-gateway  | 2024-03-12 16:04:13 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __process_remote_logging_update - 612 - Remote logging has being updated. Current logging level is: DEBUG 
tb-gateway  | 2024-03-12 16:04:13 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - process_config_request - 242 - Configuration update request received.
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler databaseHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler serviceHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler connectorHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler converterHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler tb_connectionHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler storageHandler not found. Removing from configuration...
tb-gateway  | 2024-03-12 16:04:14 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _handle_logs_configuration_update - 396 - Handler extensionHandler not found. Removing from configuration...
```
When I then go back to the overview and reopen the _general configuration_ view and go to the tab _Logs_, the remote logging is disabled again. So I am not able to enable remote logs. 

![Bildschirmfoto 2024-03-12 um 17 07 09](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/5a821cc1-f7e8-4287-a599-f44889106c2f)

This is my logs.json file after my attempts to enable the logs:

```yaml
  "version": 1,
  "disable_existing_loggers": false,
  "formatters": {
    "LogFormatter": {
      "class": "logging.Formatter",
      "format": "%(asctime)s - |%(levelname)s| - [%(filename)s] - %(module)s - %(funcName)s - %(lineno)d - %(message)s",
      "datefmt": "%Y-%m-%d %H:%M:%S"
    }
  },
  "handlers": {
    "consoleHandler": {
      "class": "logging.StreamHandler",
      "formatter": "LogFormatter",
      "level": "DEBUG",
      "stream": "ext://sys.stdout"
    }
  },
  "loggers": {
    "database": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "DEBUG",
      "propagate": false
    },
    "service": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "INFO",
      "propagate": false
    },
    "connector": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "INFO",
      "propagate": false
    },
    "converter": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "INFO",
      "propagate": false
    },
    "tb_connection": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "INFO",
      "propagate": false
    },
    "storage": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "INFO",
      "propagate": false
    },
    "extension": {
      "handlers": [
        "consoleHandler"
      ],
      "level": "INFO",
      "propagate": false
    }
  },
  "root": {
    "level": "ERROR",
    "handlers": [
      "consoleHandler"
    ]
  },
  "ts": 1710259453434
}
```
