### ISSUE TITLE
One-Way MQTT SSL

### ISSUE THREAD

**Issue by gringet** [thingsboard/thingsboard-gateway#134]
Is there a possiblity to use the gateway with one-way MQTT SSL ? If yes, how do we supply the server certificat to the gateway ?

**Comment by mp-loki** [comment]
You need to export the server certificate to a Trust Store file and configure it next to accessToken:
```
security:
    accessToken: "${GATEWAY_ACCESS_TOKEN:YOUR_TOKEN}"
    truststore: truststore.jks
    truststorePassword: password
```
