### ISSUE TITLE
[BUG] Architecture issue with latest tb-gateway image (3.4.6)

### ISSUE THREAD

**Issue by DigitalPals** [thingsboard/thingsboard-gateway#1352]
**Docker Version:** 26.0.0, build 2ae903e

**Operating System:** Ubuntu 22.04 LTS x86_64

**Description:**
When running docker compose up with a Docker Compose file, I'm encountering an "exec format error" when attaching to one of the containers. The container exits with code 0 immediately after starting.

**Steps to Reproduce:**
Create a new directory with a docker-compose.yaml file
Add a service definition like:

```
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway
    container_name: tb-gateway
    restart: always
```

Run docker compose up

**Expected Behavior:**
The container should start successfully and attach without any errors.

**Actual Behavior:**
```
Attaching to tb-gateway
myservice  | exec /bin/sh: exec format error
myservice exited with code 0
```

**Additional Context:**
The Docker image tb-gateway:latest has an architecture of "amd64"

The host system is x86_64, which should be compatible with amd64 images

This issue does not occur on older tb-gateway version (e.g. 3.4.5)

Let me know if you need any other information to investigate this issue further.
