### ISSUE TITLE
[BUG] SNMP Connectors only updates one parameter.

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1388]
**Describe the bug**
I have this configuration of a SNMP Connector:

```yaml
{
  "devices": [
    {
      "deviceName": "SNMP Test Device 1",
      "deviceType": "TestDevice",
      "ip": "host.docker.internal",
      "port": 161,
      "pollPeriod": 5000,
      "community": "public",
      "attributes": [],
      "telemetry": [
        {
          "key": "sysLocation",
          "method": "get",
          "oid": "1.3.6.1.2.1.1.7.0",
          "timeout": 6
        },
        {
          "key": "sysServices",
          "method": "get",
          "oid": "1.3.6.1.2.1.1.6.0",
          "timeout": 6
        }
      ],
      "attributeUpdateRequests": [],
      "serverSideRpcRequests": []
    }
  ],
  "logLevel": "DEBUG",
  "name": "SNMP"
}
```

I see two requests in my SNMP Container:
```
2024-05-07 10:08:36 Request var-binds: 1.3.6.1.2.1.1.7.0=<>, flags: EXACT, GET
2024-05-07 10:08:36 Response var-binds: 1.3.6.1.2.1.1.7.0=<72>
2024-05-07 10:08:32 Request var-binds: 1.3.6.1.2.1.1.6.0=<>, flags: EXACT, GET
2024-05-07 10:08:32 Response var-binds: 1.3.6.1.2.1.1.6.0=<San Francisco, California, United States>
```

But in the telemetry of SNMP Test Device 3 is only sysServices saved and updated.
![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/65412f8d-4f31-44fe-86f1-21999e46d9cd)

When I change the order in the configuration file, sysLocation gets udpated.

There are no bugs shown in the logs.

**Connector name (If bug in the some connector):**
SNMP Connector

**Versions (please complete the following information):**
 - OS: Docker
 - Thingsboard IoT Gateway version: 3.4.6
