### ISSUE TITLE
[HELP] IoTGW Performance (200dp/s cap)

### ISSUE THREAD

**Issue by ashdam** [thingsboard/thingsboard-gateway#1484]
**Describe the issue**
We are trying to stress the platform. In order to do this, we started with an OPC-UA async connector with 1000 timeseries declared and "polling" (not subscribe) every second.
Information is sent this way: IoTGateway ==> Edge PE ==> TB PE
We are getting the following information from statistics:
![image](https://github.com/user-attachments/assets/4d5c56eb-575f-482f-a46b-c10930905288)

110 events /s, memory size increasing 50 MB, but networkfraffic hasn't reached 1MB/s
![image](https://github.com/user-attachments/assets/b7937f4a-5a9f-494a-82c6-31e2ad69e3d5)

**Additionally we have verified that we have a 200dp/s cap in pubsub**

![image](https://github.com/user-attachments/assets/3185a1b9-41e4-43b9-a89b-3e0c64207821)

Do you know what mabe be happening with the cap?

**Configuration** (Attach your configuration file)
```
version: '3.4'
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway
    container_name: tb-gateway
    restart: always

    # Ports bindings - required by some connectors
    ports:
        - "5000:5000" # Comment if you don't use REST connector and change if you use another port
        # Uncomment and modify the following ports based on connector usage:
#        - "1052:1052" # BACnet connector
#        - "5026:5026" # Modbus TCP connector (Modbus Slave)
#        - "50000:50000/tcp" # Socket connector with type TCP
#        - "50000:50000/udp" # Socket connector with type UDP

    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables
    environment:
      - host=xx.xxx.xxx.xx
      - port=1883
      - accessToken=xxxxxxxxxxxxxxxxxxx

    # Volumes bind
    volumes:
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - tb-gw-extensions:/thingsboard_gateway/extensions

# Volumes declaration for configurations, extensions and configuration
volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions


```

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: Ubuntu 22
 - Thingsboard IoT Gateway version 3.5.1
 - Python version: 3.12
