### ISSUE TITLE
[BUG] Connect to Thingsboard using X.509 certificates after general configuration update

### ISSUE THREAD

**Issue by andersenthomas98** [thingsboard/thingsboard-gateway#1602]
**Describe the bug**
I am using the following `docker-compose.yaml` file to run the gateway: 

```
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway:3.5.3
    container_name: tb-gateway
    restart: always

    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables
    environment:
      - TB_GW_HOST=mqtt.thingsboard.cloud
      - TB_GW_PORT=8883
      - TB_GW_CA_CERT=credentials/ca-root.pem
      - TB_GW_PRIVATE_KEY=credentials/key.pem
      - TB_GW_CERT=credentials/cert.pem

    # Volumes bind
    volumes:
      - ./credentials:/thingsboard_gateway/config/credentials
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - tb-gw-extensions:/thingsboard_gateway/extensions

# Volumes declaration for configurations, extensions and configuration
volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions
```
The gateway connected successfully to thingsboard cloud initially using X.509 certs. However, after applying a general configuration update (using the Thingsboard IoT Gateways), I am no longer able to connect to thingsboard cloud 

**Error traceback (If available):**
```
File "/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py", line 696, in _apply_connection_config
tb-gateway  |     new_tb_client = TBClient(config if use_new_config else old_tb_client_config, old_tb_client_config_path, connection_logger)
tb-gateway  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tb-gateway  |   File "/thingsboard_gateway/gateway/tb_client.py", line 69, in __init__
tb-gateway  |     self._create_mqtt_client(config['security'])
tb-gateway  |   File "/thingsboard_gateway/gateway/tb_client.py", line 136, in _create_mqtt_client
tb-gateway  |     self.__username = str(credentials["accessToken"])
tb-gateway  |                           ~~~~~~~~~~~^^^^^^^^^^^^^^^
tb-gateway  | KeyError: 'accessToken'
tb-gateway  | 2024-11-18 12:52:35 - |WARNING| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - _revert_connection - 725 - Remote general configuration will be restored.
tb-gateway  | 2024-11-18 12:52:35 - |INFO| - [tb_client.py] - tb_client - _check_certificates - 223 - Will generate new certificate
tb-gateway  | 2024-11-18 12:52:35 - |INFO| - [tb_client.py] - tb_client - connect - 313 - Connecting to ThingsBoard...
```

**Versions (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Thingsboard IoT Gateway version:  v3.5.3
 - Docker:  v27.3.1
