### ISSUE TITLE
[HELP]Lastest 3.6.3. Modbus RTU doesnt work on RPi3

### ISSUE THREAD

**Issue by Jonnik84** [thingsboard/thingsboard-gateway#1648]
I'm using TB Gateway for testing purposes now I want to test the simple MODBUS RTU
I have hardware Raspberry Pi 3B 
Raspbian OS 64Bit Lastest stable

I use Docker installation for tb gateway
Have lastest version 3.6.3

Attaching my simple config
[modbus_serial.json](https://github.com/user-attachments/files/18378691/modbus_serial.json)

Here is LOG
[tb-gateway   Logging error.txt](https://github.com/user-attachments/files/18378708/tb-gateway.Logging.error.txt)

my hardware is working well. here is log using mbpoll:
_

> -----------------------------------------------------
> smr-admin@raspberrypi:~ $ sudo mbpoll -m rtu -a 1 -r 2  -b 9600 -d 8 -P none -s 1 /dev/ttyAMA0
> mbpoll 1.0-0 - FieldTalk(tm) Modbus(R) Master Simulator
> Copyright © 2015-2019 Pascal JEAN, https://github.com/epsilonrt/mbpoll
> This program comes with ABSOLUTELY NO WARRANTY.
> This is free software, and you are welcome to redistribute it
> under certain conditions; type 'mbpoll -w' for details.
> 
> Protocol configuration: Modbus RTU
> Slave configuration...: address = [1]
>                         start reference = 2, count = 1
> Communication.........: /dev/ttyAMA0,       9600-8N1
>                         t/o 1.00 s, poll rate 1000 ms
> Data type.............: 16-bit register, output (holding) register table
> 
> -- Polling slave 1... Ctrl-C to stop)
> [2]:    1286
> -------------------------------------------------------

Pls help me. Cant do anything further... Im not a Python engineer
Thanks

**Comment by imbeacon** [comment]
Hi @Jonnik84,

In order to connect to device from docker container you need to add forwarding of device to docker compose file.
To do this - you need to add devices section. Please find example below:

```
version: '3.4'
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway
    container_name: tb-gateway
    restart: always

    # Ports bindings - required by some connectors
    ports:
        - "5000:5000" # Comment if you don't use REST connector and change if you use another port
        # Uncomment and modify the following ports based on connector usage:
#        - "1052:1052" # BACnet connector
#        - "5026:5026" # Modbus TCP connector (Modbus Slave)
#        - "50000:50000/tcp" # Socket connector with type TCP
#        - "50000:50000/udp" # Socket connector with type UDP
    devices:
        - /dev/ttyAMA0:/dev/ttyAMA0

    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables
    environment:
      - host=host.docker.internal
      - port=1883
      - accessToken=YOUR_ACCESS_TOKEN

    # Volumes bind
    volumes:
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - tb-gw-extensions:/thingsboard_gateway/extensions

# Volumes declaration for configurations, extensions and configuration
volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions

```
