### ISSUE TITLE
[HELP] Socket is closed, connection is lost, for device ***

### ISSUE THREAD

**Issue by Ellean** [thingsboard/thingsboard-gateway#1695]
**Describe the issue**
"Socket is closed, connection is lost, for device ***"
This problem occurred at first, and it disappeared after I changed the port from `ttyUSB0` to `/dev/ttyUSB10`. When I added a new device, the problem reappeared.

**Configuration** (Attach your configuration file)
```yaml
{
  "master": {
    "slaves": [
      {
        "method": "rtu",
        "baudrate": 9600,
        "stopbits": 1,
        "bytesize": 8,
        "parity": "N",
        "strict": true,
        "unitId": 1,
        "deviceName": "***",
        "deviceType": "***",
        "timeout": 35,
        "byteOrder": "BIG",
        "wordOrder": "BIG",
        "retries": true,
        "retryOnEmpty": true,
        "retryOnInvalid": true,
        "pollPeriod": 5000,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "type": "serial",
        "attributes": [],
        "timeseries": [
          {
            "tag": "wet_temp",
            "type": "16int",
            "address": 512,
            "objectsCount": 1,
            "functionCode": 3,
            "divider": 10
          }
        ],
        "attributeUpdates": [],
        "rpc": [],
        "port": "/dev/ttyUSB10"
      }
    ]
  },
  "logLevel": "INFO",
  "name": "ModBus",
  "enableRemoteLogging": false,
  "id": "520f8975-5da3-4073-9537-f7c25185aa4f",
  "configVersion": "3.7.0"
}
```

**Connector name (If you need help with some connector/converter):**
ModBus

**Error traceback (If it was raised):**

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway version 3.7.0 (Docker Compose)
 - Python version No Python install on host
