### ISSUE TITLE
where to mount the conf dir when using docker

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard-gateway#218]
Hi i use docker-compose to run the gateway, and mount a conf dir to the container, but it can not load the mqtt-config2.yml from my mounted folder which i specified in tb-gateway.yml.

Here is some information:

docker-compose.yml：
```
version: '2'

services:
  tb-gateway:
    image: "lincoln310/tb-gateway:2.2.1-SNAPSHOT"
    environment:
      - GATEWAY_ACCESS_TOKEN=
      - TB_HOST=
      - TB_PORT=
    entrypoint: /run-application.sh

    restart: always
    volumes:
      - tb-gw-conf:/usr/share/tb-gateway/conf
      - tb-gw-log:/var/log/tb-gateway
volumes:
  tb-gw-conf:
    driver: local
    driver_opts:
      type: none
      device: /root/tb/gw3/conf
      o: bind
  tb-gw-log:
    driver: local
    driver_opts:
      type: none
      device: /root/tb/gw3/log
      o: bind
```

tb-gateway.yml
```gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: 
        port: 
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "${GATEWAY_ACCESS_TOKEN}"
      remoteConfiguration: false
      extensions:
        -
          id: "mqtt"
          type: "MQTT"
          extensionConfiguration: mqtt-config2.json
```

I attached to the container, and found a soft link from /usr/share/tb-gateway/bin/tb-gateway.yml to /usr/share/tb-gateway/conf/tb-gateway.yml. 
Then i changed the config from mqtt-config.yml to mqtt-config2.yml, and renamed the mqtt-config.yml to mqtt-config2.yml in /root/tb/gw3/conf.
Then it failed to start because of missing the mqtt-config2.yml.
