### ISSUE TITLE
Cannot connect to OPC server

### ISSUE THREAD

**Issue by komis1** [thingsboard/thingsboard-gateway#243]
Hello,
Apologies for the noob question, I have setup an OPC server on a Rasberry Pi, and I'm trying to get the TB Gateway to connect to it, without success. The connector.log shows error
`''2020-02-06 13:22:50' - INFO - opcua_connector - 86 - Starting OPC-UA Connector'
''2020-02-06 13:22:50' - DEBUG - opcua_connector - 97 - error on connection to OPC-UA server.'
''2020-02-06 13:22:50' - ERROR - opcua_connector - 98 - 'Client' object has no attribute 'load_type_definitions''`

I have updated the opcua python package to the latest version (0.98.9). My TB installation runs on a Ubuntu VM, otherwise working without problems. I have setup the gateway as a device and configured the tb_gateway.yaml correctly.
On the Raspberry Pi, I am running the server_example.py of the python-opcua package from [https://github.com/FreeOpcUa/python-opcua/blob/master/examples/server-example.py](url). Using the ProSys OPC browser I can connect and retrieve the data successfully. Same applies when running the client_example.py code (from python-opcua). 
I have also tried running the Open62541 server, again I can connect successfully with the ProSys browser and the client_example.py script, but not with the gateway.

Any ideas what might be causing this? Thanks in advance!

[edit: just updated to the latest release, but the problem persists (error lines 99 and 100)]

**Comment by zbeacon** [comment]
Hi @komis1 

Thanks for your interest in ThingsBoard IoT Gateway. Your problem looks really strange because I used the same server for development. Please share your configuration for opcua connector, I will try to repeat this situation. Also, please provide information about your Raspberry:
What system was used?
What version of Raspberry did you use?

**Comment by komis1** [comment]
Hi @zbeacon,
Thank you for your reply. I know, I've been trying to get my head around it but can't find anything that would cause it. 
On the Linux VM (where tb is installed) I'm using Python 3.6.9.
On the Raspberry (RP4, 4Gb RAM), I'm using the latest Raspbian. Nothing else is running on the Pi. As I said, I don't think the problem is there, because I can see the OPCUA server just fine using a multitude of clients, both from the local machine, and from remote machines.

Here is the connector config for the gateway on the Linux VM
```{
  "server": {
    "name": "OPC-UA Default Server",
    "url": "opc.tcp://<raspberry ip>:4840/freeopcua/server/",
    "scanPeriodInMillis": 10000,
    "timeoutInMillis": 5000,
    "security": "Basic128Rsa15",
    "identity": {
      "type": "anonymous"
    },
    "mapping": [
      {
        "deviceNodePattern": "Root\\.Objects\\.Device1",
        "deviceNamePattern": "Device ${Root\\.Objects\\.Device1\\.serialNumber}",
        "attributes": [
          {
            "key": "temperature",
            "path": "${TemperatureAndHumiditySensor\\.Temperature}"
          }
        ],
        "timeseries": [
          {
            "key": "humidity",
            "path": "${Root\\.Objects\\.Device1\\.TemperatureAndHumiditySensor\\.Humidity}"
          },
          {
            "key": "batteryLevel",
            "path": "${Battery\\.batteryLevel}"
          }
        ],
        "rpc_methods": [
          {
            "method": "multiply",
            "arguments": [2, 4]
          }
        ],
        "attributes_updates": [
          {
            "attributeOnThingsBoard": "deviceName",
            "attributeOnDevice": "Root\\.Objects\\.Device1\\.serialNumber"
          }
        ]
      }
    ]
  }
}
```

And the general gateway config (yaml)
```
thingsboard:
  host: 127.0.0.1
  port: 1883
  remoteConfiguration: false
  security:
    accessToken: <my gateway access token>
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:

#  -
#    name: MQTT Broker Connector
#    type: mqtt
#    configuration: mqtt.json
#
#  -
#    name: Request Connector
#    type: request
#    configuration: request.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
  -
    name: OPC-UA Connector
    type: opcua
    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector
```
