### ISSUE TITLE
[BUG] Server connection timeout is always set to 10 seconds

### ISSUE THREAD

**Issue by david114** [thingsboard/thingsboard-gateway#249]
I'm experiencing a weird behaviour using the OPC-UA Connector.
Although i set `timeoutInMillis: 1000` the connection-timeout to thingsboard is always 10 seconds.
i want to update my telemetry data every 1, 2 or 3 seconds, is there any other parameter that i need to set?

**Comment by david114** [comment]
Here some additional info:

**My opcua.json:**
```
{
  "server": {
    "name": "OPC-UA Default Server",
    "url": "localhost:4840/freeopcua/server/",
    "scanPeriodInMillis": 1000,
    "timeoutInMillis": 1000,
    "showMap": true,
    "security": "Basic128Rsa15",
    "identity": {
      "type": "anonymous"
    },
    "mapping": [
      {
        "deviceNodePattern": "Root\\.Objects\\.main_folder",
        "deviceNamePattern": "Machine",
        "attributes": [
          {
            "key": "Sensor_2",
            "path": "${sensor2}"
          }
        ],
        "timeseries": [
          {
            "key": "Sensor_1",
            "path": "${sensor1}"
          }
        ]
      }
    ]
  }
}
```

**My tb_gateway.yaml:**
```
thingsboard:
  host: <my-ip>
  port: 1883
  remoteConfiguration: true
  security:
    accessToken: <my-accesstoken>
storage:
  type: file
  data_folder_path: ./data/
  max_file_count: 100
  max_read_records_count: 100
  max_records_per_file: 10000
connectors:
#  -
#   name: MQTT Broker Connector
#   type: mqtt
#   configuration: mqtt.json
#
#  -
#    name: Request Connector
#    type: request
#    configuration: request.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
  -
    name: OPC-UA Connector
    type: opcua
    configuration: opcua.json

#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector
```

With this configuration, is it not possible to send data every second to thingsboard, why?
