### ISSUE TITLE
Thingsboard-gateway V2.2 Communication with Server

### ISSUE THREAD

**Issue by mirtaheri** [thingsboard/thingsboard-gateway#255]
Hello!
we have installed and followed the instructions for the thingsboard gateway but failed to stablish communication with Thingsboardf server. It is worth to mention that with previous versions (JAVA) the implementation is successfull, so I wonder if I am missing correct configuration for the current (python) version, with some slight format changes w.r.t to the past.
The gateway should interface with a sensor (namely weather station) device through mqtt connector and send the data to the server.
The weather station -through `weewex` mqtt interface- is publishing successfully the sensor values.

The `tb_gateway.yaml` -communication to sever- is configured as following:

```
thingsboard:
  host: mydomain.it
  port: 1883
  remoteConfiguration: false
  security:
    accessToken: UVXXXXXXXXXXXX
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json
```

The  `mqtt.json` which is used as gateway connector, is set (minimal setup) like below:

```
{
  "broker": {
    "name": "Weather Station Broker",
    "host": "localhost",
    "port": 1883,
    "security": {
      "type": "anonymous"
    }
  },
  "mapping": [
    {
      "topicFilter": "WeatherSensors",
      "converter": {
        "type": "json",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${outTemp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${outHumidity}"
          }
        ],
        "deviceNameJsonExpression": "${WeatherStationName}"
      }
    }
  ]
}
```
WeatherSensors is the topic on which `weewx-mqtt`, and `outTemp`, `outHumidity` are fields in the payload.

I receive in the dashboard (server-side) these keys: `eventsProduced` and `eventsSent` and haveing all fields in the `mqtt.json` (`connectRequests`, `disconnectRequests`, `attributeUpdates `and `serverSideRpc`) I get also `mqttbrokerconnectorEventsProduced` and `mqttbrokerconnectorEventsSent`.
So, I assume that connectin to server is not a problem, but at the same time I am sure about the sensor (weewex) topic and payload.
