### ISSUE TITLE
[HELP] Dockerized Thingsboard + Thingsboard Gateway -> Nothing is published and/or created

### ISSUE THREAD

**Issue by tmontanaro** [thingsboard/thingsboard-gateway#270]
**Describe the issue**
I have Thingsboard (in Docker) configured with MQTT port 1883.
Then Thingsboard gateway (in Docker) configured to communicate with Thingsboard and to futher listen on an external MQTT broker set on port 1885 (you can see the configuration files at the end of the message)
The MQTT connector is set to listen for new data on topic '/topicprova/prova/'.

I expect that everytime a new data is published on that topic:
a) a new message is seen on the log
b) a new device is created on Thingsboard.
However, if I try to publish on that topic nothing happens

**Configuration** (Attach your configuration file)
1. tb_gateway.yaml
   ```
   thingsboard:
     host: 172.17.0.4
     port: 1883
     security:
       accessToken: <tokenOfTheGatewayDevice>
   storage:
     type: memory
     read_records_count: 10
     max_records_count: 1000
   connectors:
     -
       name: MQTT Broker Connector
       type: mqtt
       configuration: mqtt.json
   #
   #  -
   #    name: Modbus Connector
   #    type: modbus
   #    configuration: modbus.json
   #
   #  -
   #    name: Modbus Connector
   #    type: modbus
   #    configuration: modbus_serial.json
   #
   #  -
   #    name: BLE Connector
   #    type: ble
   #    configuration: ble.json
   #
   #  -
   #    name: OPC-UA Connector
   #    type: opcua
   #    configuration: opcua.json
   #
   #  -
   #    name: Custom Serial Connector
   #    type: serial
   #    configuration: custom_serial.json
   #    class: CustomSerialConnector
   ```
2. mqtt.json
   ```
    {
      "broker": {
        "name":"Default Broker",
        "host":"172.17.0.1",
        "port":1885,
        "security": {
          "type": "anonymous"
        }
      },
      "mapping": [
        {
          "topicFilter": "/topicprova/prova/",
          "converter": {
            "type": "json",
            "deviceNameJsonExpression": "${entityId}",
            "deviceTypeJsonExpression": "${entityType}",
            "timeout": 60000,
            "attributes": [
              {
                "type": "string",
                "key": "receivingEntityId",
                "value": "${id}"
              }
            ],
            "timeseries": [
              {
                "type": "double",
                "key": "lastUpdate",
                "value": "${lastUpdate}"
              }
            ]
          }
        }
      ],
      "connectRequests": [
        {
          "topicFilter": "sensors/connect",
          "deviceNameJsonExpression": "${$.SerialNumber}"
        },
        {
          "topicFilter": "sensor/+/connect",
          "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/connect)"
        }
      ],
      "disconnectRequests": [
        {
          "topicFilter": "sensors/disconnect",
          "deviceNameJsonExpression": "${$.SerialNumber}"
        },
        {
          "topicFilter": "sensor/+/disconnect",
          "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/disconnect)"
        }
      ],
      "attributeUpdates": [
        {
          "deviceNameFilter": "SmartMeter.*",
          "attributeFilter": "uploadFrequency",
          "topicExpression": "sensor/${deviceName}/${attributeKey}",
          "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
        }
      ],
      "serverSideRpc": [
        {
          "deviceNameFilter": ".*",
          "methodFilter": "echo",
          "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
          "responseTopicExpression": "sensor/${deviceName}/response/${methodName}/${requestId}",
          "responseTimeout": 10000,
          "valueExpression": "${params}"
        },
        {
          "deviceNameFilter": ".*",
          "methodFilter": "no-reply",
          "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
          "valueExpression": "${params}"
        }
      ]
    }
   ```

**How I tried to send data**
`mosquitto_pub -d -h 192.168.1.215 -p 1885 -t "/topicprova/prova/" -m '{"serialNumber":"Teo", "sensorType": "Farm","id":"Teo", "lastUpdate":1585733355}'`

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Error traceback (If it was raised):**
There is no error

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Thingsboard version -> unknown, the one installed 10 minutes ago with `sudo docker run -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -d -v ~/.mytb-data:/data -v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb-postgres`
 - Thingsboard IoT Gateway version -> unknown, the one installed 10 minutes ago with `sudo docker run -it -v ~/.tb-gateway/logs:/var/log/thingsboard-gateway -v ~/.tb-gateway/extensions:/var/lib/thingsboard_gateway/extensions -v ~/.tb-gateway/config:/etc/thingsboard-gateway/config --name tb-gateway -d --restart always thingsboard/tb-gateway`

**Comment by tmontanaro** [comment]
##How to reproduce the use case##

1. Install the Thingsboard Docker container
   ```
   sudo docker run -d -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -v ~/.mytb-data:/data -v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb-postgres
   ```
2. Install the Thingsboard Gateway Docker container
   ```
   sudo docker run -d -it -v ~/.tb-gateway/logs:/var/log/thingsboard-gateway -v ~/.tb-gateway/extensions:/var/lib/thingsboard_gateway/extensions -v ~/.tb-gateway/config:/etc/thingsboard-gateway/config --name tb-gateway --restart always thingsboard/tb-gateway
   ```
3. Stop the Thingsboard Gateway
   ```
   sudo docker container ls
   <GET THE ID of the container>
   sudo docker stop <container-ID>
   ```
4. Modify the parameters to link the gateway to Thingsboard
   * Open a browser and open the Thingsboard interface
      `http://192.168.1.215:9090`
   * Login with the "Tenant Administrator user"
   * Enter the "Device" section
   * Create a new Device and put a tick in the "Is gateway" option
   * Copy the generated Token Id
5. Come back on your terminal (the one used to install the containers)
6. Modify the file `~/.tb-gateway/config/tb_gateway.yaml` (172.17.0.3 is the address of the Thingsboard container and the accessToken is the one copied at point 4)
   ```
   thingsboard:
     host: 172.17.0.3
     port: 1883
     security:
       accessToken: 6MEdYnniARHDx5TrIhV0
   storage:
     type: memory
     read_records_count: 10
     max_records_count: 1000
   connectors:
   
     -
       name: MQTT Broker Connector
       type: mqtt
       configuration: mqtt.json
   #
   #  -
   #    name: Modbus Connector
   #    type: modbus
   #    configuration: modbus.json
   #
   #  -
   #    name: Modbus Connector
   #    type: modbus
   #    configuration: modbus_serial.json
   #
   #  -
   #    name: BLE Connector
   #    type: ble
   #    configuration: ble.json
   #
   #  -
   #    name: OPC-UA Connector
   #    type: opcua
   #    configuration: opcua.json
   #
   #  -
   #    name: Custom Serial Connector
   #    type: serial
   #    configuration: custom_serial.json
   #    class: CustomSerialConnector
   ```
7. MOSQUITTO:
   * Install MOSQUITTO
      ```
      sudo apt-get update
      sudo apt-get install mosquitto
      ```
   * Stop Mosquitto
      ```
      sudo systemctl start mosquitto.service
      ```
   * Change default port
      ```
      sudo nano /etc/mosquitto/mosquitto.conf
      ```
   * Add the following line to the file
      ```
      port 1885
      ```
   * Restart Mosquitto
      ```
      sudo systemctl start mosquitto.service
      ```
8. Modify the file `~/.tb-gateway/config/mqtt.json` (172.17.0.1 is the address of the host machine) to connect to the MQTT broker run in host (parent) machine.  
   ```
     "broker": {
       "name":"Default Broker",
       "host":"172.17.0.1",
       "port":1885,
       "security": {
         "type": "anonymous"
       }
     },
   ...
   ```

## Configure Thingsboard Gateway to accept all messages arriving on the MQTT broker with topic "/topicprova/prova/"
* We want to send all data to the Thingsboard Gateway on topic "/topicprova/prova/", so that, then, it creates a new device everytime a new entity-Id arrives.

* Open the file `~/.tb-gateway/config/mqtt.json`
* Add the following topic to the mapping section:
```
   {
      "topicFilter": "/topicprova/prova/",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${entityId}",
        "deviceTypeJsonExpression": "${entityType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "receivedEntityId",
            "value": "${id}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "lastUpdate",
            "value": "${lastUpdate}"
          }
        ]
      }
   }
```
