### ISSUE TITLE
[HELP] Dockerized Thingsboard + Thingsboard Gateway -> New device created but no data is published

### ISSUE THREAD

**Issue by tmontanaro** [thingsboard/thingsboard-gateway#274]
**Describe the issue**
I configured Thingsboard and Thingsboard gateway to work in this way:
- new data are pushed on 1 device that is a gateway
- if the device does not exist, it will create it
- push received data on the (new if it did not exist, otherwise, existing) device.

As I understand from the official documentation, this task should be done through the Thingsboard gateway and the MQTT connector.
You can find all the steps followed to create such a scenario [here](https://github.com/thingsboard/thingsboard-gateway/issues/270#issuecomment-607145803), and the configuration in the following.

Then I tried to push new data (without creating any new converter, but by using the default one) through the following instruction:
`mosquitto_pub -d -h 192.168.1.215 -p 1885 -t "/sensor/data" -m '{"serialNumber":"1234", "sensorType":"Farm", "sensorModel":"ciao", "temp":12,"hum":34}'`

But, even though the device is created with the right name (serialNumber) and the right Type (sensorType), no data and/or attributes are inserted inside.

**Am I doing anything wrong?**

**Configuration** (Attach your configuration file)
1. tb_gateway.yaml
```
thingsboard:
  host: 172.18.0.150
  port: 1883
  remoteConfiguration: false
  security:
    accessToken: Q65vseTJreuQ8RVtqTDK
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:

  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json

#  -
#    name: Request Connector
#    type: request
#    configuration: request.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua
#    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector
```

2. mqtt.json
```
{
  "broker": {
    "name":"Default Broker",
    "host":"172.18.0.1",
    "port":1885,
    "security": {
      "type": "anonymous"
    }
  },
  "mapping": [
    {
      "topicFilter": "/sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${serialNumber}",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
    {
      "topicFilter": "/sensor/+/data",
      "converter": {
        "type": "json",
        "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/data)",
        "deviceTypeTopicExpression": "Thermometer",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
    {
      "topicFilter": "/custom/sensors/+",
      "converter": {
        "type": "custom",
        "extension": "CustomMqttUplinkConverter",
        "extension-config": {
            "temperatureBytes" : 2,
            "humidityBytes" :  2,
            "batteryLevelBytes" : 1
        }
      }
    }
  ],
  "connectRequests": [
    {
      "topicFilter": "sensor/connect",
      "deviceNameJsonExpression": "${SerialNumber}"
    },
    {
      "topicFilter": "sensor/+/connect",
      "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/connect)"
    }
  ],
  "disconnectRequests": [
    {
      "topicFilter": "sensor/disconnect",
      "deviceNameJsonExpression": "${SerialNumber}"
    },
    {
      "topicFilter": "sensor/+/disconnect",
      "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/disconnect)"
    }
  ],
  "attributeUpdates": [
    {
      "deviceNameFilter": "SmartMeter.*",
      "attributeFilter": "uploadFrequency",
      "topicExpression": "sensor/${deviceName}/${attributeKey}",
      "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
    }
  ],
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": "echo",
      "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "responseTopicExpression": "sensor/${deviceName}/response/${methodName}/${requestId}",
      "responseTimeout": 10000,
      "valueExpression": "${params}"
    },
    {
      "deviceNameFilter": ".*",
      "methodFilter": "no-reply",
      "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "valueExpression": "${params}"
    }
  ]
}
```

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Error traceback (If it was raised):**
No error: the device is created with the right type, but neither attributes nor data are inserted in the device

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version -> the latest installed with Docker (re-downloaded 2 hours ago)
 - Thingsboard version -> the latest installed with Docker (re-downloaded 2 hours ago)

**Comment by zbeacon** [comment]
Hi @tmontanaro,

Thank you for your feedback, I will try to repeat this issue tomorrow and write to you.

**Comment by zbeacon** [comment]
Hi @tmontanaro,

I repeated your installation, but I use 172.18.0.1 instead of 172.18.0.150 and it works correctly.
I tested data send by following command - `mosquitto_pub -d -h localhost -p 1887 -u user -P x -t "/sensor/data" -m '{"serialNumber":"SOME DEVICE", "sensorType":"Farm", "sensorModel":"ciao", "temp":12,"hum":34}'`

The ThingsBoard created device with name "SOME DEVICE" and gots data from message correctly (I have also installed mosquitto broker (dockerized) on port 1887).

Could you try to replace 172.18.0.150 and send data again? 
To check is the gateway connected - you can go to the "ATTRIBUTES" tab of the gateway device, select "Server attributes" from drop list and check attribute value and updated time of attribute with name "active". It will true if the gateway connected successfully.
Please, let me know about results.

**Comment by tmontanaro** [comment]
Hi @zbeacon,
thank you very much for your feedback!
At first: yes, the gateway is connected, as you can see from the attached picture

![tempThingsboard](https://user-images.githubusercontent.com/6121394/78539847-84621480-77f3-11ea-9dbe-ae4172238662.png)

Then, I tried to push the same data you pushed by using the following command:
`mosquitto_pub -d -h localhost -p 1885 -u user -P x -t "/sensor/data" -m '{"serialNumber":"SOME DEVICE", "sensorType":"Farm", "sensorModel":"ciao", "temp":12,"hum":34}'`  
**(as you can notice, I didn't specify user and password)**  

but in the following image you can see that the device was actually created but without any attribute:
![temp2Thingsboard](https://user-images.githubusercontent.com/6121394/78540868-11599d80-77f5-11ea-915c-e3042a58702d.png)


Thus, the only difference among my and your request to pub data is in the user and password (+ the IP addresses). Where did you take username and password?

**Comment by tmontanaro** [comment]
I've also tried to change IP addresses but nothing changed!
Let's summarize again all the procedure with new addresses.
I executed the following commands:
1. install mosquitto
   `sudo apt-get install mosquitto`
2. Verify that mosquitto is working:
   * terminal 1:
     `mosquitto_sub -h localhost -p 1883 -v -t "#"`
   * terminal 2 (look in terminal 1 if you see the message):
     `mosquitto_pub -d -h localhost -p 1883 -t "/topic1" -m 'hello'`
3. Change the mosquitto port:
   * `sudo nano /etc/mosquitto/mosquitto.conf`
   * change port to 1885: `port 1885` in last line
4. Restart mosquitto:
   * `sudo systemctl start mosquitto.service`
5. Install the Thingsboard network in docker
    `sudo docker network create -d bridge thingsboard-network --gateway 172.18.0.254 --ip-range 172.18.0.0/16 --subnet 172.18.0.0/16`
6. Install the Thingsboard container in docker:
    `sudo docker run -d -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -v ~/.mytb-data:/data -v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always --net thingsboard-network --ip 172.18.0.1 thingsboard/tb-postgres`
7. Install the Thingsboard Gateway container in docker:
   `sudo docker run -d -it -v ~/.tb-gateway/logs:/var/log/thingsboard-gateway -v ~/.tb-gateway/extensions:/var/lib/thingsboard_gateway/extensions -v ~/.tb-gateway/config:/etc/thingsboard-gateway/config --name tb-gateway --restart always --net thingsboard-network --ip 172.18.0.2 thingsboard/tb-gateway`
8. Stop the `tb-gateway` container
9. Change tb-gateway settings:
   `sudo nano .tb-gateway/config/tb_gateway.yaml`  
   ```
    thingsboard:
      host: 172.18.0.1
      port: 1883
      remoteConfiguration: false
      security:
        accessToken: Q65vseTJreuQ8RVtqTDK
    storage:
      type: memory
      read_records_count: 100
      max_records_count: 100000
    connectors:
      -
        name: MQTT Broker Connector
        type: mqtt
        configuration: mqtt.json
   ```
10. Change mqtt connector settings:
   `sudo nano .tb-gateway/config/mqtt.json`
   ```
    {
      "broker": {
        "name":"Default Broker",
        "host":"172.18.0.254",
        "port":1885,
        "security": {
          "type": "anonymous"
        }
      },
      "mapping": [
        {
          "topicFilter": "/sensor/data",
          "converter": {
            "type": "json",
            "deviceNameJsonExpression": "${serialNumber}",
            "deviceTypeJsonExpression": "${sensorType}",
            "timeout": 60000,
            "attributes": [
              {
                "type": "string",
                "key": "model",
                "value": "${sensorModel}"
              }
            ],
            "timeseries": [
              {
                "type": "double",
                "key": "temperature",
                "value": "${temp}"
              },
              {
                "type": "double",
                "key": "humidity",
                "value": "${hum}"
              }
            ]
          }
        },
      ...
   ```
11. Restart the `tb-gateway` container.
12. Push a data on the MQTT broker:
   `mosquitto_pub -d -h localhost -p 1885 -u user -P x -t "/sensor/data" -m '{"serialNumber":"SOME DEVICE", "sensorType":"Farm", "sensorModel":"ciao", "temp":12,"hum":34}'`
