### ISSUE TITLE
[HELP] How to set up Storage configuration

### ISSUE THREAD

**Issue by everardogentil** [thingsboard/thingsboard-gateway#343]
Hi!
I am trying ThingsBoard Gateway at Raspberry PI 3 (RPI3) with Ubuntu 18.04 server. I have **34 energy meters** connected to RPI3 over **Modbus/TCP**. Each meter should send **34 analogue 32float values** to ThingsBoard Server each **10 seconds**. 

Today I am using the following configuration but when I connect more than 15 modbus devices the gateway doesn't publish any date to the ThingsBoard server.

```
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
```

**I would like to know what is the recommended configuration for storage in the tb_gateway.yaml.**

Thanks in advamce.

**Versions:**
 - Hardware: Raspberry PI 3 B
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version: 2.4.1
 - Python version: 3.6.9
