### ISSUE TITLE
POST method using request connector[HELP]

### ISSUE THREAD

**Issue by meghanajose** [thingsboard/thingsboard-gateway#368]
Trying to work on POST method with Request connector. Not receiving data in thingsboard. I used Postman to post the data.
this is the body:
{
  "key":56,
  "id" :5
}

**Configuration**
```
  host: demo.thingsboard.io
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  security:
    accessToken: EAwVlViQR9c257A6R6CB
storage:
  type: memory
  read_records_count: 10
  max_records_count: 1000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:
  -
#    name: MQTT Broker Connector
#    type: mqtt
#    configuration: mqtt.json

#  -
#     name: Modbus Connector
#     type: modbus
#     configuration: modbus.json
#
#  -
#     name: Modbus Connector
#     type: modbus
#     configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua
#    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
      name: REQUEST Connector
      type: request
      configuration: request.json
#
#  -
#    name: CAN Connector
#    type: can
#    configuration: can.json
#
#  -
#    name: BACnet Connector
#    type: bacnet
#    configuration: bacnet.json
#
#  -
#    name: ODBC Connector
#    type: odbc
#    configuration: odbc.json
#
#  -
#   name: REST Connector
#    type: rest
#    configuration: rest.json
#
#  -
#    name: SNMP Connector
#    type: snmp
#    configuration: snmp.json
#
#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector)
```
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**

**Connector name (If you need help with some connector/converter):** Request connector 
```
{
  "host": "https://reqres.in",
  "SSLVerify": true,
  "security": {
    "type": "anonymous"
  },
  "mapping": [
    {
      "url": "api/users",
      "httpMethod": "POST",
      "httpHeaders": {
        "ACCEPT": "application/json"
      },
      "allowRedirects": true,
      "timeout": 0.5,
      "scanPeriod": 1,
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "test",
        "deviceTypeJsonExpression": "default",
        "attributes": [
          {
            "key": "serialNumber",
            "type": "string",
            "value": "${Id}"
          }
        ],
        "telemetry": [
          {
            "key": "Maintainer",
            "type": "string",
            "value": "${key}"
          }


        ]
      }
    }
  ],
  "attributeUpdates": [
    {
      "httpMethod": "POST",
      "httpHeaders": {
        "CONTENT-TYPE": "application/json"
      },
      "timeout": 0.5,
      "tries": 3,
      "allowRedirects": true,
      "deviceNameFilter": "SD.*",
      "attributeFilter": "send_data",
      "requestUrlExpression": "test/${deviceName}/${attributeKey}",
      "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
    }
  ],
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": "echo",
      "requestUrlExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "responseTimeout": 1,
      "httpMethod": "GET",
      "valueExpression": "${params}",
      "timeout": 0.5,
      "tries": 3,
      "httpHeaders": {
        "Content-Type": "application/json"
      }
    },
    {
      "deviceNameFilter": ".*",
      "methodFilter": "no-reply",
      "requestUrlExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "httpMethod": "POST",
      "valueExpression": "${params}",
      "httpHeaders": {
        "Content-Type": "application/json"
      }
    }
  ]
}

```
    

**Error traceback (If it was raised):**
```
""2020-08-11 13:19:44" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 52 - Cannot find the value from the input data"
""2020-08-11 13:19:44" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 52 - Cannot find the value from the input data"
""2020-08-11 13:19:44" - ERROR - [tb_utility.py] - tb_utility - 62 - No telemetry and attributes in data: {"deviceName": "test", "deviceType": "default", "attributes": [], "telemetry": []}"
""2020-08-11 13:19:44" - ERROR - [tb_gateway_service.py] - tb_gateway_service - 314 - Data from REQUEST Connector connector is invalid."

```

**Versions (please complete the following information):**
 - OS: [windows 10]
 - Thingsboard IoT Gateway version [2.5.0]
 - Python version[.3.7]
![Screenshot (75)](https://user-images.githubusercontent.com/67738385/89873277-cce17280-dbd7-11ea-914e-97fe6d0a7eda.png)

gateway is getting updated with event produced and sent
