### ISSUE TITLE
[HELP] Thingsboard IoT Gateway without Persistant Storage

### ISSUE THREAD

**Issue by yeduy** [thingsboard/thingsboard-gateway#491]
Hello,

When the connection with Thingsboard is lost, I want incoming data to disappear until I reconnect. So I don't want data stored on Gateway. How can I do that?

```
storage:
  type: memory
  read_records_count: 10
  max_records_count: 1000

```
How do I set up here for this?

Thank you

**Comment by zbeacon** [comment]
Hi @yeduy ,

Thank you for your interest in ThingsBoard IoT gateway.
You can set something like this:

```yaml
storage:
  type: memory
  read_records_count: 1
  max_records_count: 1
```
According to this configuration - the gateway will process messages one by one end send them only when message is processed and won't take more in case when connection is lost.
