### ISSUE TITLE
[HELP] Thingsboard gateway stops sending data from opcua server

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard-gateway#552]
**Describe the issue**
The gateway has succesfully sent data to thingsboard, where i can find it in the "latest telemetry" of the device. But has now stopped sending in new data, except for 4 values from the gateway itself:
	opc-uaconnectorEventsProduced
	opc-uaconnectorEventsSent
	eventsSent
	eventsProduced
All other values except these get updated.
Screenshot from thingsboard's latest telemetry:
![image](https://user-images.githubusercontent.com/32327026/129539950-8cd71d8e-a079-4a83-9a6d-006c4947384e.png)

**Configuration**
<details>
  <summary>opcua.json</summary>
  
  ```json
{
	"server": {
		"disableSubscriptions": true,
		"identity": {
			"type": "anonymous"
		},
		"mapping": [
			{
				"attributes": [],
				"deviceNamePattern": "Device01",
				"deviceNodePattern": "Root\\.Objects\\.M241-M251 data",
				"deviceTypePattern": "rolbrug",
				"timeseries": [
					{
						"key": "Bed_Claxon",
						"path": "ns=2;s=GVL.Bed_Claxon"
					},
					{
						"key": "Bed_Gr_Sn_B",
						"path": "ns=2;s=GVL.Bed_Gr_Sn_B"
					},
					{
						"key": "Bed_Gr_Sn_K",
						"path": "ns=2;s=GVL.Bed_Gr_Sn_K"
					},
					{
						"key": "Bed_Gr_Sn_T",
						"path": "ns=2;s=GVL.Bed_Gr_Sn_T"
					},
					{
						"key": "Bed_Keuze_T1",
						"path": "ns=2;s=GVL.Bed_Keuze_T1"
					},
					{
						"key": "Bed_Keuze_T2",
						"path": "ns=2;s=GVL.Bed_Keuze_T2"
					},
					{
						"key": "Bed_Achteruit_B",
						"path": "ns=2;s=GVL.Bed_Achteruit_B"
					}
				]
			}
		],
		"name": "OPC-UA Default Server",
		"scanPeriodInMillis": 5000,
		"security": "Basic128Rsa15",
		"showMap": true,
		"subCheckPeriodInMillis": 500,
		"timeoutInMillis": 10000,
		"url": "10.10.0.100:4840"
	}
}
  ```
</details>

<details>
  <summary>tb-gateway.yaml</summary>
  
```yaml
connectors:
- configuration: opcua.json
  name: OPC-UA Connector
  type: opcua
storage:
  max_records_count: 1000
  read_records_count: 10
  type: memory
thingsboard:
  host: tb-gateway.****.com
  port: 1883
  remoteConfiguration: true
  remoteShell: false
  security:
    accessToken: 0000
```
</details>

**Connector name:**
OPC-Connector

**Error traceback (If it was raised):**

Can't find any errors, and in my rule chain in thingsboard i only get these 4 values in Debug
![image](https://user-images.githubusercontent.com/32327026/129539531-3c4ff7b0-c312-48df-a7e2-6f9211549c0c.png)

**Versions (please complete the following information):**
 - OS: Raspbian Buster
 - Thingsboard IoT Gateway version: 2.6.1
 - Python version: 3.7.3
