### ISSUE TITLE
[BUG] Gateway low throughput for rest connector 

### ISSUE THREAD

**Issue by dwjbosman** [thingsboard/thingsboard-gateway#556]
**Describe the bug**

I am having an issue with thingsboard gateway running on a Raspberry Pi 3B.

I am using the rest connector. The Rest connector is called by 4 sensors  with an interval of 5 seconds. So 4 requests per 5 seconds. The measurements themselves consist of about 5 attributes and <5 timeseries values.

It seems the gateway can't keep up. After some time a get

```
"Exception happened during processing of request from ('127.0.0.1', 53450)
Aug 24 11:22:20 novus-d74f778e python3[30806]: Traceback (most recent call last):
Aug 24 11:22:20 novus-d74f778e python3[30806]: File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
Aug 24 11:22:20 novus-d74f778e python3[30806]: self.process_request(request, client_address)
Aug 24 11:22:20 novus-d74f778e python3[30806]: File "/usr/lib/python3.7/socketserver.py", line 665, in process_request
Aug 24 11:22:20 novus-d74f778e python3[30806]: t.start()
Aug 24 11:22:20 novus-d74f778e python3[30806]: File "/usr/lib/python3.7/threading.py", line 847, in start
Aug 24 11:22:20 novus-d74f778e python3[30806]: _start_new_thread(self._bootstrap, ())
Aug 24 11:22:20 novus-d74f778e python3[30806]: RuntimeError: can't start new thread"
```
In the log I also see the following when starting up:

```

Aug 24 11:54:48 novus-d74f778e python3[23513]:  * Serving Flask app 'REST Connector' (lazy loading)
Aug 24 11:54:48 novus-d74f778e python3[23513]:  * Environment: production
Aug 24 11:54:48 novus-d74f778e python3[23513]:    WARNING: This is a development server. Do not use it in a production deployment.
Aug 24 11:54:48 novus-d74f778e python3[23513]:    Use a production WSGI server instead.
Aug 24 11:54:48 novus-d74f778e python3[23513]:  * Debug mode: off

```
Log entry while the system is running:

```
Aug 24 12:02:11 novus-d74f778e python3[23513]: [STREAM ONLY] 2021-08-24 12:02:11,812 - INFO - [rest_connector.py] - rest_connector - 311 - CONVERTER CONFIG: {'type': 'json', 'deviceNameExpression': '${tags.name}', 'deviceTypeExpression': 'default', 'attributes': [{'type': 'string', 'key': 'type', 'value': '${tags.type}'}, {'type': 'string', 'key': 'model', 'value': '${tags.model}'}, {'type': 'string', 'key': 'device_serial_nr', 'value': '${tags.device_serial_nr}'}, {'type': 'string', 'key': 'sensor_serial_nr', 'value': '${tags.sensor_serial_nr}'}, {'type': 'string', 'key': 'slot_nr', 'value': '${tags.slot_nr}'}], 'timeseries': [{'type': 'double', 'key': 'delta_pressure', 'value': '${fields.delta_pressure}'}, {'type': 'double', 'key': 'delta_pressure_raw', 'value': '${fields.delta_pressure_raw}'}, {'type': 'double', 'key': 'dpr_temperature', 'value': '${fields.dpr_temperature}'}, {'type': 'double', 'key': 'temperature', 'value': '${fields.temperature}'}, {'type': 'double', 'key': 'humidity', 'value': '${fields.humidity}'}, {'type': 'double', 'key': 'pm2_5', 'value': '${fields.pm2_5}'}, {'type': 'double', 'key': 'pm10', 'value': '${fields.pm10}'}, {'type': 'double', 'key': 'pm1_0', 'value': '${fields.pm1_0}'}]}
Aug 24 12:02:14 novus-d74f778e python3[23513]: [STREAM ONLY] 2021-08-24 12:02:14,048 - INFO - [rest_connector.py] - rest_connector - 316 - CONVERTED_DATA: {'deviceName': '00000001-0-Humidity', 'deviceType': 'default', 'attributes': [{'type': 'SHTC3'}, {'model': 'Humidity'}, {'device_serial_nr': '00000001'}, {'sensor_serial_nr': '4294967295'}, {'slot_nr': '0'}], 'telemetry': [{'ts': 1629799268, 'values': {'humidity': 61605.25}}]}
```

I have configured the gateway to cache to a file (on a RAM disc). The state_file.txt position is to be equal to the number of lines in the data file. This indicates to me that the bottleneck is at the rest connector and not at the connection from gateway to thingsboard cloud.

What could be the issue?

**Connector name (If bug in the some connector):**
[Rest]

Configuration

```
thingsboard:
  host: thingsboard.cloud
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statsSendPeriodInSeconds: 3600
  checkConnectorsConfigurationInSeconds: 60
  security:
    accessToken:  ----REMOVED---
  qos: 1
storage:
#type: memory
#  read_records_count: 50
#  max_records_count: 100000
  type: file
  data_folder_path: /tmp/tb_data/
  max_file_count: 10
  max_read_records_count: 10
  max_records_per_file: 10000
connectors:
#  - name: MQTT Broker Connector
#    type: mqtt
#    configuration: mqtt.json

#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua
#    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
#    name: REQUEST Connector
#    type: request
#    configuration: request.json
#
#  -
#    name: CAN Connector
#    type: can
#    configuration: can.json
#
#  -
#    name: BACnet Connector
#    type: bacnet
#    configuration: bacnet.json
#
#  -
#    name: ODBC Connector
#    type: odbc
#    configuration: odbc.json
#
   -
     name: REST Connector
     type: rest
     configuration: rest.json
```

Rest connector config

```
{
  "host": "127.0.0.1",
  "port": "5000",
  "mapping":[
    {
      "endpoint": "/gateway",
      "HTTPMethods": [
        "POST", "GET"
      ],
      "security":
      {
        "type": "anonymous"
      },
      "converter": {
        "type": "json",
        "deviceNameExpression": "${tags.name}",
        "deviceTypeExpression": "default",
        "attributes": [
          {
            "type": "string",
            "key": "type",
            "value": "${tags.type}"
          },
          {
            "type": "string",
            "key": "model",
            "value": "${tags.model}"
          },
          {
            "type": "string",
            "key": "device_serial_nr",
            "value": "${tags.device_serial_nr}"
          },
          {
            "type": "string",
            "key": "sensor_serial_nr",
            "value": "${tags.sensor_serial_nr}"
          },
          {
            "type": "string",
            "key": "slot_nr",
            "value": "${tags.slot_nr}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "delta_pressure",
            "value": "${fields.delta_pressure}"
          },
          {
            "type": "double",
            "key": "delta_pressure_raw",
            "value": "${fields.delta_pressure_raw}"
          },
          {
            "type": "double",
            "key": "dpr_temperature",
            "value": "${fields.dpr_temperature}"
          },
          {
            "type": "double",
            "key": "temperature",
            "value": "${fields.temperature}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${fields.humidity}"
          },
          {
            "type": "double",
            "key": "pm2_5",
            "value": "${fields.pm2_5}"
          },
          {
            "type": "double",
            "key": "pm10",
            "value": "${fields.pm10}"
          },
          {
            "type": "double",
            "key": "pm1_0",
            "value": "${fields.pm1_0}"
          }
        ]
      }
    }
  ],
  "attributeUpdates": [
      {
        "HTTPMethod": "POST",
        "SSLVerify": false,
        "httpHeaders": {
          "CONTENT-TYPE": "application/json"
        },
        "security": {
          "type": "basic",
          "username": "user",
          "password": "passwd"
        },
        "timeout": 0.5,
        "tries": 3,
        "allowRedirects": true,
        "deviceNameFilter": ".*REST$",
        "attributeFilter": "data",
        "requestUrlExpression": "sensor/${deviceName}/${attributeKey}",
        "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
      }
  ],
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": "echo",
      "requestUrlExpression": "http://127.0.0.1:5001/${deviceName}",
      "responseTimeout": 1,
      "HTTPMethod": "GET",
      "valueExpression": "${params}",
      "timeout": 0.5,
      "tries": 3,
      "httpHeaders": {
        "Content-Type": "application/json"
      },
      "security": {
        "type": "anonymous"
      }
    },
    {
      "deviceNameFilter": ".*",
      "methodFilter": "no-reply",
      "requestUrlExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "HTTPMethod": "POST",
      "valueExpression": "${params}",
      "httpHeaders": {
        "Content-Type": "application/json"
      }
    }
  ]
}
```

**Error traceback (If available):**

See above

**Versions (please complete the following information):**
 - OS: [Debian buster, Raspberry Pi 3B]
 - Thingsboard IoT Gateway version [2.7]
 - Python version: Python 3.7.3
