### ISSUE TITLE
[HELP] OTA Updates not working with gateway

### ISSUE THREAD

**Issue by feg624** [thingsboard/thingsboard-gateway#563]
**Describe the issue**
We're evaluating Thingsboard for device management. Our objective is to install the Thingsboard gateway into an edge device, which then connects to the source devices. We're interested in the OTA Update feature to run on the gateway (to run a software update on the edge device)... we were able to open a RPC Shell from the dashboard into the gateway, but we haven't had luck with OTA Update. Question is: does the gateway have OTA Update feature out of the box? or do we need to code some script (adopting the SDK) in order to have that capability on the edge device (gateway)?

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**
```
thingsboard:
  host: mytb
  port: 1883
  remoteShell: true
  remoteConfiguration: true
  security:
    accessToken: xxx
#    caCert: "./config/mqttserver.pub.pem"
  qos: 1
```

**Connector name (If you need help with some connector/converter):**
N/A

**Error traceback (If it was raised):**
N/A

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway version 2.6 and 2.7
 - Python version 3.9
