### ISSUE TITLE
[BUG] OPC-UA connector ERROR. 'uacrypto' not defined when running docker image. 

### ISSUE THREAD

**Issue by artturimW** [thingsboard/thingsboard-gateway#635]
**Describe the bug**
Trying to connect to PLC with OPC-UA connector. Using docker-compose with thingsboard/tb-gateway:latest image. 
Trying to connect using following config:  

security: Basic256Sha256
type: cert.PEM
cert: aaa
publickey: bbb
mode: SignAndEncrypt

Same config is working when running tb_gateway without docker. I also managed to get tb_gateway working with docker when using only "anonymous" security.

Error says  'uacrypto' is not defined and then ua_client returning "error:StatusCode(BadSecurityPolicyRejected)

Docker-compose:
```
version: '3.8'

services:
  tbg-1:
    image: thingsboard/tb-gateway:latest
    restart: always
    networks:
      - gateway
    volumes:
      - ./config:/thingsboard_gateway/config
      - ./extensions:/thingsboard_gateway/extensions
      - tbg-1-logs:/thingsboard_gateway/logs:z

networks:
  gateway:
    driver: bridge

volumes:
  tbg-1-logs:
    driver: local
```

**Connector name (If bug in the some connector):**
OPC-UA Connector

**Error traceback (If available):**
![image](https://user-images.githubusercontent.com/86042541/142593230-865efcdd-e360-4b10-a88b-b1799481eb8f.png)

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version 2.9 /latest
 - Python version 3.7
