### ISSUE TITLE
[HELP] K8s gateway with 2 replicas

### ISSUE THREAD

**Issue by ardilom2** [thingsboard/thingsboard-gateway#651]
Hello,
I created an image of thingsboard-gateway (based on v2.6) and it works fine, but now I tried to run it with a replica and it keeps failing and restarting and I don't understand why. What am I doing wrong?

**Configuration**
```
thingsboard:
  host: $THINGSBOARD_HOST
  port: $THINGSBOARD_PORT
  remoteShell: false
  remoteConfiguration: false
  security:
    accessToken: $THINGSBOARD_GATEWAY_TOKEN
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
connectors:
  - name: REST Connector
    type: rest
    configuration: rest.json
```

**Error traceback (If it was raised):**
![image](https://user-images.githubusercontent.com/82225828/145884277-25a4525a-3574-4b4b-ad17-d7dd11353efe.png)

**Versions (please complete the following information):**
 - OS: Debian 10
 - Thingsboard IoT Gateway version 2.6
 - Python version 3.9
