### ISSUE TITLE
[HELP] Unable to start TB Gateway 3.0.1 & Question about Remote Configurator

### ISSUE THREAD

**Issue by jeffreylauck** [thingsboard/thingsboard-gateway#690]
**Describe the issue**
I have done a clean installation of the TB Gateway on my Pi Zero today, however I am unable to start the gateway. Is it something to do with new v3.0.1 of the Gateway?

Also, I am reinstalling the TB Gateway in the hope of making the "Remote Configurator" to work on the gateway. I was trying to use the Remote Configurator widget on the server to configure the gateway connectors but had no luck yet. May I know if it is a completed feature, and if any documentation is available?

Thanks!

**Configuration** (Attach your configuration file)
I am using the config from the doc
```
thingsboard:
  host: 192.168.0.24
  port: 1883
  security:
    accessToken: ***REMOVED***
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:

  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json

```

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

**Error traceback (If it was raised):**
```
Illegal instruction
```

**Versions (please complete the following information):**
 - OS: Raspbian 11
 - Thingsboard IoT Gateway version: 3.0.1
 - Python version: 3.9
