### ISSUE TITLE
thingsboard gateway installation problem

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard-gateway#764]
Wanted to install thingsboard gateway following the instruction in:
https://thingsboard.io/docs/iot-gateway/getting-started/

It went well to some extent and have this configuration file under /etc/thingsboard-gateway/config/tb_gateway.yaml

```
thingsboard:
  host: thingsboard.cloud
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statsSendPeriodInSeconds: 3600
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  security:
    accessToken: MY_GW_ACCESS_TOKEN
...
...
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json
```

Change the Access Token with my gateway access token. 

Restarted it.

systemctl restart thingsboard-gateway

```
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
'thingsboard-gateway.service'を再起動するには認証が必要です。(it says that to restart thingsboard-gateway I need to authorize)
Authenticating as: kenkyu,,, (kenkyu)
Password:
==== AUTHENTICATION COMPLETE ===
```

But after that, when I used to check status, it gives the following error message.  

```
$ systemctl status thingsboard-gateway
● thingsboard-gateway.service - ThingsBoard Gateway
     Loaded: loaded (/etc/systemd/system/thingsboard-gateway.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-03-03 20:03:51 JST; 33min ago
    Process: 178691 ExecStart=/usr/bin/python3 -c from thingsboard_gateway.tb_gateway import daemon; daemon() (code=exited, status=1/FAILURE)
   Main PID: 178691 (code=exited, status=1/FAILURE)

 3月 03 20:03:51 spf python3[178691]:     create_key=_descriptor._internal_create_key,
 3月 03 20:03:51 spf python3[178691]: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
 3月 03 20:03:51 spf systemd[1]: Started ThingsBoard Gateway.
 3月 03 20:03:51 spf systemd[1]: thingsboard-gateway.service: Main process exited, code=exited, status=1/FAILURE
 3月 03 20:03:51 spf systemd[1]: thingsboard-gateway.service: Failed with result 'exit-code'.
 3月 03 20:03:51 spf systemd[1]: thingsboard-gateway.service: Scheduled restart job, restart counter is at 5.
 3月 03 20:03:51 spf systemd[1]: Stopped ThingsBoard Gateway.
 3月 03 20:03:51 spf systemd[1]: thingsboard-gateway.service: Start request repeated too quickly.
 3月 03 20:03:51 spf systemd[1]: thingsboard-gateway.service: Failed with result 'exit-code'.
 3月 03 20:03:51 spf systemd[1]: Failed to start ThingsBoard Gateway.
```

Any help would be very much appreciated. 

 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard version 3.3.2
 - Thingsboard IoT Gateway version [3.0.1-1]
 - Python version[3.8]

**Comment by debacs83** [comment]
Sorry, I made a mistake last time. I forgot to change the host from ' thingsboard.cloud' to 'localhost'. After editing this part, I restarted. But still the status remain same, with similar 'Failed to start ThingsBoard Gateway' message. 

Any other file to edit or check?

**Comment by samson0v** [comment]
Hi @debacs83, please, send the whole tb_gateway.yaml file.

**Comment by debacs83** [comment]
Hi @samson0v,
Thanks!  Here is my 'tb_gateway.yaml' file. Have tried with 'host: demo.thingsboard.io' with a different ACCESS_TOKEN, from my 'demo.thingsboard.io' account. But the result was same. Any help would be very much appreciated. 

```
thingsboard:
  #host: demo.thingsboard.io
  host: localhost
  port: 1883
  security:
    accessToken: MY_ACCESS_TOKEN
storage:
  type: memory
  read_records_count: 10
  max_records_count: 100
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:

  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json

#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua
#    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json

#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector
```

**Comment by samson0v** [comment]
@debacs83, it is the actual config file, it seems that you are using the old version of the Gateway. Please, update it to the newest version.
```
thingsboard:
  host: thingsboard.cloud
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statsSendPeriodInSeconds: 3600
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken:
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
#  type: sqlite
#  data_file_path: ./data/data.db
#  messages_ttl_check_in_hours: 1
#  messages_ttl_in_days: 7
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:
#  -
#    name: MQTT Broker Connector
#    type: mqtt
#    configuration: mqtt.json

#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua
#    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
#    name: REQUEST Connector
#    type: request
#    configuration: request.json
#
#  -
#    name: CAN Connector
#    type: can
#    configuration: can.json
#
#  -
#    name: BACnet Connector
#    type: bacnet
#    configuration: bacnet.json
#
#  -
#    name: ODBC Connector
#    type: odbc
#    configuration: odbc.json
#
  -
    name: REST Connector
    type: rest
    configuration: rest.json
#
#  -
#    name: SNMP Connector
#    type: snmp
#    configuration: snmp.json
#
#  -
#    name: FTP Connector
#    type: ftp
#    configuration: ftp.json
#
#  -
#    name: Socket TCP/UDP Connector
#    type: socket
#    configuration: socket.json
#
# ========= Customization ==========
#
#
#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector
#
#  -
#    name: GRPC Connector 1
#    key: auto
#    type: grpc
#    configuration: grpc_connector_1.json

```
