### ISSUE TITLE
[HELP] IoT Gateway configuration - Advanced security: TLS + Private Key

### ISSUE THREAD

**Issue by alexcorvis84** [thingsboard/thingsboard-gateway#781]
**Describe the issue**

I'm trying to test connection of the Thingsboard IoT Gateway to Thingsboard platform via **Advanced security: TLS + Private Key** **without** success :-( 

There's no log message that could help me debug what's happening. Please check my configuration and 'error' traceback log below attached.

I wonder if the port should be instead 8883? There's no info about it in the online documentation for this case, so I'm not sure if it must be changed or not.

_Please note FYI:_ The connection of the gateway through Access Token is working ok but I need to setup TLS + Private Key.

**Configuration**
```
thingsboard:
  maxPayloadSizeBytes: 8192
  host: test-device2.hostname.example
  port: 1883
  remoteShell: true
  remoteConfiguration: false
  statsSendPeriodInSeconds: 3600
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  security:
    privateKey: /home/user/key.pem
    caCert: /home/user/tb-server-chain.pem
    cert: /home/user/cert.pem
#     accessToken: ****
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
#  type: sqlite
#  data_file_path: ./data/data.db
#  messages_ttl_check_in_hours: 1
#  messages_ttl_in_days: 7
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:
#  -
#    name: MQTT Broker Connector
#    type: mqtt
#    configuration: mqtt.json

#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
  -
    name: Modbus Connector
    type: modbus
    configuration: modbus_serial.json
```

**Error traceback (If it was raised):**
```
""2022-03-17 08:50:20" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 93 - Gateway starting..."
""2022-03-17 08:50:20" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 98 - ThingsBoard IoT gateway version: 3.0.1"
```

**Versions (please complete the following information):**
 - OS: **Raspbian GNU/Linux 10 (buster)**
 - Thingsboard IoT Gateway version **3.0.1**
 - Python version **3.7.3**
