### ISSUE TITLE
Timeout Error Connecting to Thingsboard (MQTT)

### ISSUE THREAD

**Issue by Bucknalla** [thingsboard/thingsboard-gateway#86]
Hi,

I'm having an issue connecting to my Thingsboard Server (my own instance). I am getting a time out error appearing in my /var/log/tb-gateway/tb-gateway.log

`2018-06-06 13:46:51,051 [main] ERROR o.t.g.s.gateway.MqttGatewayService - Unable to connect to ThingsBoard. Connection timed out after [10000] milliseconds
`

My tb-gateway.yml looks as follows:

```
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "${GATEWAY_HOST:My_Own_Host_IP}"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "${GATEWAY_ACCESS_TOKEN:My_Own_Token}"
      remoteConfiguration: true
      extensions:
        -
          id: "http"
          type: "HTTP"
extensionConfiguration: http-config.json
```

Do I need to set up my own MQTT broker? The instructions in the documentation seem to suggest that all I need to do is change the host IP and add my access token and the gateway should appear in my thingboard devices page.

Any help would be greatly appreciated!

Thanks,

Alex
