### ISSUE TITLE
[HELP] Limits on amount of data you can send through a single Gateway?

### ISSUE THREAD

**Issue by gregwinn** [thingsboard/thingsboard-gateway#877]
**Describe the issue**
I have a very busy Gateway that gets about 80 to 150 messages a min. After looking at this issue [826](https://github.com/thingsboard/thingsboard-gateway/issues/826) I see they had to split up into multiple gateways. I am having the same issue with devices showing up in Thingsboard however telemetry data is not saved consistently. Just like in #826 I am getting data sometimes and other times it's just the device name and that's it.

I have checked the logs and everything looks normal (all logs are set to DEBUG) - I am not seeing any ERROR or WARNING.

I am using sqlite3 for storage on the gateway and that seems to be working well - no errors.

**Configuration** (Attach your configuration file)
```
thingsboard:
  host: mythingsboardUrl.com
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: true
    statsSendPeriodInSeconds: 3600
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: TOKEN
storage:
  type: sqlite
  data_file_path: /etc/thingsboard-gateway/data/data.db
  messages_ttl_check_in_hours: 1
  messages_ttl_in_days: 2

connectors:

  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json

```

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway version: Latest
 - Python version: 3.9
