### ISSUE TITLE
[HELP] Request Connector data_to_storage RPC problem

### ISSUE THREAD

**Issue by peterandthejetsons** [thingsboard/thingsboard-gateway#998]
Hello,

I have the Thingsboard Gateway v3.2 installed in a docker environment on a Ubuntu 20.04 server. I have a smart thermostat connected to TB Gateway via Request Connector. POST messages are works fine (with these messages I can control the thermostat), but I'd like to use GET messages to update the control widget's status (like Knob control) to show the current temperature, but I'm always get the following error message: 

```
""2022-11-16 16:59:45" - |DEBUG| - [connectionpool.py] - connectionpool - _make_request - 456 - https://api.blablabla.com:443 "GET /api/blablabla?id=blablabla HTTP/1.1" 200 689"
""2022-11-16 16:59:45" - |ERROR| - [request_connector.py] - request_connector - __send_request - 227 - 'converter'"
Traceback (most recent call last):
  File "/thingsboard_gateway/connectors/request/request_connector.py", line 206, in __send_request
    data_to_storage = [url, request["converter"]]
KeyError: 'converter'
```

The answer from the API is the following:

```
{
status:"ok"
time_exec:"0.060059070587158"
time_server:"1553777827"
}
```

My tb_gateway.yaml config is the following:

```
thingsboard:
  host: 192.168.1.1
  port: 1883
  remoteShell: true
  remoteConfiguration: true
  statsSendPeriodInSeconds: 3600
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: blablabla
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
connectors:
  -
    name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json
  -
    name: REQUEST Connector
    type: request
    configuration: request.json
```

My request.json config is the following:

```
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": "getTherm",
      "requestUrlExpression": "api/blablabla?id=blablabla",
      "responseTimeout": 5,
      "httpMethod": "GET",
      "valueExpression": "${params}",
      "timeout": 5,
      "tries": 3,
      "httpHeaders": {
        "Content-Type": "application/json",
        "Authorization": "Bearer blablabla"
      }
    },
    {
      "deviceNameFilter": ".*",
      "methodFilter": "setTherm",
      "requestUrlExpression": "api/blablabla?id=blablabla&id2=blablabla&mode=blablabla&temp=${params}",
      "httpMethod": "POST",
      "valueExpression": "${params}",
      "httpHeaders": {
        "Accept": "application/json",
        "Authorization": "Bearer blablabla"
      }
    }
  ]

```
I'd like to ask for your help in this issue. If you need further information, please let me know.

**Connector name:**
- Request connector
- Request connector's converter

**Versions:**
 - OS: Ubuntu 20.04
 - Docker: Docker version 20.10.7
 - Thingsboard IoT Gateway version 3.2
 - Python version 3.10.8
